name = "nubium-telemetry"
main = "worker.ts"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "stats.nubium.rocks", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "nubium-telemetry"
database_id = "ab4a35b8-92c6-459d-a7a4-a3d912d6b734"
